---
title: "Talks"
author: "Lisa DeBruine"
format: 
  html:
    css: style.scss
---

* [Academic Lead for Good Research Practice](ALfGRP) for Engineering 2026-01-13
* [Fake it until you make it: How and why to simulate research data](fake-it-2024/) Glasgow SPN M&Ms 2024-11-26
* [Teaching Reproducible Research](teach-repro-2025) for UofG Maths and Stats seminar 2025-11-25
* [Using Data Simulation in the Classroom](Leuven-2025) for Leuven Statistics Days 2025-05-26
* [Replicability of results in the context of private non-sharable data](rostock-datasim) for Rostock Open Science Workshop 2025-03-18
* [Advanced GitHub](rostock-github) for Rostock Open Science Workshop 2025-03-17
* [Good Research Practice Advisors](GRP-advisors) 2025-03-11
* [Academic Lead for Good Research Practice](ALfGRP-2024) for CoSE R&I 2024-10-17
* [Professional Skils: Open Research](prof-skills-open-res) 2024-10-07
* [Data Simulation with {faux} for mixed designs](lmemsim-2024/) 2024-04-09
* [Open Research MVLS](UofG-open-res-MVLS) 2024-02-26
* [Fake it until you make it: How and why to simulate research data](RGlasgow-fake-it-2024/) RGlasgow 2024-01-25 
* [Data Simulation and Code Review](CompCogSci-2023) U of Edinburgh CompCogSci 2023-11-09
* [Ethics and Open Research](UofG-open-res-ethics) UofG CoSE Ethics 2023-10-06
* [Replicability and Generalisability in Face Research](rep-gen-faces/) VU 2023-09-21
* [Code Review](code-review/) UofG 2023-08-31
* [Fake it until you make it: How and why to simulate research data](EMPSEB-fake-it-2023/) EMPSEB 
* [Code Review](RIOT-code-review-2022/) RIOT Science Club 2022-11-21
* [What is Open Research?](UofG-OR-PGR-2022/) UofG PGR Webinar 2022-11-01
* [UofG Open Research Workshop](UofG-open-res/) 2022-10-25
